---
title: "A1"
output: html_document
---
```{r}
library(RCTD)
library(Matrix)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  out.width = "100%"
)
```

```{r}
refdir <- system.file("extdata",'Reference/Vignette',package = 'RCTD') # directory for the reference
counts <- read.csv(file.path(refdir,"dge.csv")) # load in counts matrix
rownames(counts) <- counts[,1]; counts[,1] <- NULL # Move first column to rownames
meta_data <- read.csv(file.path(refdir,"meta_data.csv")) # load in meta_data (barcodes, clusters, and nUMI)
cell_types <- meta_data$cluster; names(cell_types) <- meta_data$barcode # create cell_types named list
cell_types <- as.factor(cell_types) # convert to factor data type
nUMI <- meta_data$nUMI; names(nUMI) <- meta_data$barcode # create nUMI named list
```

```{r}
reference <- Reference(counts, cell_types, nUMI)
```
```{r}
print(dim(reference@counts)) #observe Digital Gene Expression matrix
table(reference@cell_types) #number of occurences for each cell type
```

```{r}
saveRDS(reference, file.path(refdir,'SCRef.rds'))
```

```{r SpatialRNA, results = 'hide', fig.height = 6, fig.width = 6}
datadir <- system.file("extdata",'SpatialRNA/Vignette',package = 'RCTD') # directory for sample Slide-seq dataset
counts <- read.csv(file.path(datadir,"MappedDGEForR.csv")) # load in counts matrix
coords <- read.csv(file.path(datadir,"BeadLocationsForR.csv"))
rownames(counts) <- counts[,1]; counts[,1] <- NULL # Move first column to rownames
rownames(coords) <- coords$barcodes; coords$barcodes <- NULL # Move barcodes to rownames
nUMI <- colSums(counts) # In this case, total counts per pixel is nUMI
```

```{r}
puck <- SpatialRNA(coords, counts, nUMI)
```

```{r}
print(dim(puck@counts)) # observe Digital Gene Expression matrix
hist(log(puck@nUMI,2)) # histogram of log_2 nUMI
print(head(puck@coords)) # start of coordinate data.frame
barcodes <- colnames(puck@counts) # pixels to be used (a list of barcode names).
```
```{r}
plot_puck_continuous(puck, barcodes, puck@nUMI, ylimit = c(0,round(quantile(puck@nUMI,0.9))), 
                     title ='plot of nUMI') 
```

```{r DEgenes}
myRCTD <- create.RCTD(puck, reference, max_cores = 1)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')
```

```{r results, results = 'hide',  fig.width = 8, fig.height=8}
results <- myRCTD@results
# normalize the cell type proportions to sum to 1.
norm_weights = sweep(results$weights, 1, rowSums(results$weights), '/') 
cell_type_names <- myRCTD@cell_type_info$info[[2]] #list of cell type names
spatialRNA <- myRCTD@spatialRNA
resultsdir <- 'RCTD_Plots' ## you may change this to a more accessible directory on your computer.
dir.create(resultsdir)
```

```{r results2, results = 'hide', fig.width = 8, fig.height=8}
# make the plots 
# Plots the confident weights for each cell type as in full_mode (saved as 
# 'results/cell_type_weights_unthreshold.pdf')
plot_weights(cell_type_names, spatialRNA, resultsdir, norm_weights) 
# Plots all weights for each cell type as in full_mode. (saved as 
# 'results/cell_type_weights.pdf')
plot_weights_unthreshold(cell_type_names, spatialRNA, resultsdir, norm_weights) 
# Plots the weights for each cell type as in doublet_mode. (saved as 
# 'results/cell_type_weights_doublets.pdf')
plot_weights_doublet(cell_type_names, spatialRNA, resultsdir, results$weights_doublet, 
                     results$results_df) 
# Plots the number of confident pixels of each cell type in 'full_mode'. (saved as 
# 'results/cell_type_occur.pdf')
plot_cond_occur(cell_type_names, resultsdir, norm_weights, spatialRNA)
# makes a map of all cell types, (saved as 
# 'results/all_cell_types.pdf')
plot_all_cell_types(results$results_df, spatialRNA@coords, cell_type_names, resultsdir)

# doublets
#obtain a dataframe of only doublets
doublets <- results$results_df[results$results_df$spot_class == "doublet_certain",] 
# Plots all doublets in space (saved as 
# 'results/all_doublets.pdf')
plot_doublets(spatialRNA, doublets, resultsdir, cell_type_names) 
# Plots all doublets in space for each cell type (saved as 
# 'results/all_doublets_type.pdf')
plot_doublets_type(spatialRNA, doublets, resultsdir, cell_type_names) 
# a table of frequency of doublet pairs 
doub_occur <- table(doublets$second_type, doublets$first_type) 
# Plots a stacked bar plot of doublet ocurrences (saved as 
# 'results/doublet_stacked_bar.pdf')
plot_doub_occur_stack(doub_occur, resultsdir, cell_type_names) 
```

```{r}
k <- 2
prob <- matrix(rep(0, k*100), nrow = 100)
weight <- matrix(rep(0, 100), nrow = 100)
```

```{r}
alpha <- c(0.5, 0.5)
miu   <- runif(k)
sigma <- runif(k)
```

```{r}
for (j in 1:k) {
    prob[, j]   <- sapply(counts, dnorm, miu[j], sigma[j])
    weight[, j] <- alpha[j] * prob[, j]
  }
  row_sum <- rowSums(weight)
  prob    <- weight/row_sum
```
```{r}
oldalpha <- alpha
  oldmiu   <- miu
  oldsigma <- sigma

```

```{r}
  for (j in 1:k) {
    sum1     <- sum(prob[, j])
    sum2     <- sum(counts*prob[, j])
    alpha[j] <- sum1/100
    miu[j]   <- sum2/sum1
    sum3     <- sum(prob[, j]*(counts-miu[j])^2)
    sigma[j] <- sqrt(sum3/sum1)
  }
```
```{r}
threshold <- 1e-5
  if (sum(abs(alpha - oldalpha)) < threshold & 
      sum(abs(miu - oldmiu))     < threshold & 
      sum(abs(sigma - oldsigma)) < threshold) break
  myRCTD('step', step, 'alpha', alpha, 'miu', miu, 'sigma', sigma, '\n')
}
```
```{r}
categorical_mixture_EM <- function(Y, mu) {
G=nrow(Y)
K=19
Y = as.matrix(myRCTD@spatialRNA@counts)
df_Y <- as.data.frame(Y)
df_Y
str(df_Y)

mu = matrix(0, nrow=nrow(ref_counts_matched), ncol=19)
df_mu <- as.data.frame(mu)
df_mu
str(df_mu)
 ## initialization
Ztemp = runif( K*G, min=0.1, max = 1) #we define a vector with length k*g
Z = matrix(data=Ztemp , nrow=G, ncol = 19, byrow = TRUE)
#construct the matrix with K row,G column
betas = runif( K, min=0.1, max = 1)
#construct a vector of beta

 for (iter in seq(100)) {

  # E step: update Z
for (j in seq(G)){
    for (k in seq(K)){
    dot=betas[k]%*% mu[,j]
    Z[k][j] = (betas[k] * mu[k][j])/dot
    }
    }
# M step: update beta
         for (j in seq(G)){
      lambda=sum(Y_count_matrix[j] %*% z_tem[,k])
      betas[k] = Y[,j] %*% Z[,j] / lambda
    }
 }
 return(Z, betas)
    
    ## Check convergence
    if (it > min_iter && logLik_new - logLik_old < logLik_threshold) {
      break
    } else {
      logLik_old <- logLik_new
    }
}

```


```{r}
categorical_mixture_EM(Y,mu)
```


```{r}
K=19
Y = as.matrix(myRCTD@spatialRNA@counts)
df_Y <- as.data.frame(Y)
df_Y
str(df_Y)

#mu = matrix(0, nrow=nrow(ref_counts_matched), ncol=19)
#df_mu <- as.data.frame(mu)
#df_mu
#str(df_mu)
 ## initialization
Ztemp = runif( K*G, min=0.1, max = 1) #we define a vector with length k*g
Z = matrix(data=Ztemp , nrow=G, ncol = 19, byrow = TRUE)
#construct the matrix with K row,G column
betas = runif( K, min=0.1, max = 1)
#construct a vector of beta
```
```{r}
Y = as.matrix(myRCTD@spatialRNA@counts)


## reference to generate mu matrix
ref_counts = as.matrix(myRCTD@reference@counts)
ref_counts = ref_counts + 0.1


mm = match(row.names(Y), row.names(ref_counts))
ref_counts_matched = ref_counts[mm, ]

ctype = as.numeric(myRCTD@reference@cell_types)

mu = matrix(0, nrow=nrow(ref_counts_matched), ncol=19)
for (k in seq(19)){
  mu[, k] = rowSums(ref_counts_matched[, ctype==k])
  mu[, k] = mu[, k] / sum(mu[, k])
}

```


```{r}
i=1
Yi = Y[, i]

for (j in seq(G)){
    for (k in seq(K)){
      dot=betas %*% mu[j,]
      Z[j,k]=(betas[k] * mu[j,k])/dot
    }
  
# M step: update beta
for (j in seq(G)){  
lambda=Y[, 1] %*% Z[,k]
      betas[k] = Y[,1] %*% Z[,k] / lambda
    }
}


```

```{r}
dot=betas[k]%*% mu[,j]
```


